import React from 'react';
import { useNavigate } from 'react-router-dom';
import { FileText, Download, ArrowLeft, Calendar, Shield } from 'lucide-react';

const EmployeeDocuments = () => {
    const navigate = useNavigate();

    const documents = [
        {
            id: 1,
            name: 'Annual Assessment Report 2025',
            type: 'Performance Review',
            date: '15 Jan 2026',
            category: 'HR',
            size: '245 KB'
        },
        {
            id: 2,
            name: 'Employment Contract',
            type: 'Legal Document',
            date: '01 Jan 2024',
            category: 'HR',
            size: '512 KB'
        },
        {
            id: 3,
            name: 'Company Policies Handbook',
            type: 'Reference',
            date: '01 Jan 2026',
            category: 'HR',
            size: '1.2 MB'
        },
        {
            id: 4,
            name: 'Benefits Enrollment Form',
            type: 'Benefits',
            date: '10 Dec 2025',
            category: 'HR',
            size: '128 KB'
        },
    ];

    const handleDownload = (doc) => {
        const content = `DOCUMENT: ${doc.name}

Type: ${doc.type}
Category: ${doc.category}
Date: ${doc.date}
Size: ${doc.size}

This is a sample document from the Employee Self-Service Portal.
Generated by SmartHRM System.

In production, this would download the actual document from the server.`;

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${doc.name.replace(/\s/g, '_')}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="flex flex-col h-full w-full bg-gray-50 font-sans p-8 overflow-y-auto">
            {/* Header */}
            <div className="flex items-center gap-4 mb-6">
                <button
                    onClick={() => navigate(-1)}
                    className="p-2 hover:bg-gray-200 rounded transition-colors"
                >
                    <ArrowLeft size={20} className="text-gray-600" />
                </button>
                <div className="flex-1">
                    <h1 className="text-2xl font-bold text-gray-800 flex items-center gap-3">
                        <FileText className="text-blue-600" /> My Documents
                    </h1>
                    <p className="text-xs font-bold text-gray-500 uppercase mt-1">Employee Document Center</p>
                </div>
            </div>

            {/* Notice */}
            <div className="bg-blue-50 border border-blue-200 p-4 rounded-lg mb-6 flex items-start gap-3">
                <Shield size={20} className="text-blue-600 mt-0.5" />
                <div>
                    <h3 className="text-sm font-bold text-blue-900">Secure Document Access</h3>
                    <p className="text-xs text-blue-700 mt-1">
                        All documents are confidential and for your personal use only. Do not share with unauthorized parties.
                    </p>
                </div>
            </div>

            {/* Documents Grid */}
            <div className="grid gap-4">
                {documents.map((doc) => (
                    <div
                        key={doc.id}
                        className="bg-white p-5 rounded-lg border border-gray-200 shadow-sm hover:shadow-md transition-all flex items-center justify-between"
                    >
                        <div className="flex items-center gap-4 flex-1">
                            <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center text-blue-600">
                                <FileText size={24} />
                            </div>
                            <div className="flex flex-col flex-1">
                                <span className="text-base font-bold text-gray-800">{doc.name}</span>
                                <div className="flex items-center gap-4 mt-1">
                                    <span className="text-xs text-gray-500">{doc.type}</span>
                                    <span className="text-xs text-gray-400">•</span>
                                    <span className="text-xs text-gray-500 flex items-center gap-1">
                                        <Calendar size={12} /> {doc.date}
                                    </span>
                                    <span className="text-xs text-gray-400">•</span>
                                    <span className="text-xs text-gray-500">{doc.size}</span>
                                </div>
                            </div>
                        </div>

                        <button
                            onClick={() => handleDownload(doc)}
                            className="flex items-center gap-2 px-5 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-bold uppercase transition-all"
                        >
                            <Download size={16} /> Download
                        </button>
                    </div>
                ))}
            </div>

            {/* Footer */}
            <div className="mt-8 flex justify-center">
                <p className="text-xs text-gray-400">
                    Documents are retained according to company policy. Contact HR for assistance.
                </p>
            </div>
        </div>
    );
};

export default EmployeeDocuments;
