import React, { useState, useEffect } from 'react';
import {
    FileText, Download, Calendar, Lock, Loader2
} from 'lucide-react';
import { api } from '../../services/api';

const MyPayslips = () => {
    const [loading, setLoading] = useState(false);
    const [history, setHistory] = useState([]);
    const [activeUser] = useState(JSON.parse(localStorage.getItem('currentUser') || '{}'));

    const fetchHistory = async () => {
        if (!activeUser.email) return;
        try {
            setLoading(true);
            const response = await api.fetchPayrolls({
                email: activeUser.email
            });
            if (response.success) {
                setHistory(response.data.map(p => ({
                    id: p.id,
                    period: p.period,
                    date: p.paymentDate ? new Date(p.paymentDate).toLocaleDateString() : new Date(p.createdAt).toLocaleDateString(),
                    net: new Intl.NumberFormat('en-JM', { style: 'currency', currency: 'JMD' }).format(parseFloat(p.netSalary)),
                    status: p.status
                })));
            }
        } catch (err) {
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchHistory();
    }, [activeUser.id]);

    const handleDownload = (slip) => {
        // Since we don't have real PDF rendering, we generate a nicely formatted text blob
        const content = `========================================================
             OFFICIAL PAYSLIP - ${slip.period.toUpperCase()}
========================================================

EMPLOYEE NAME: ${activeUser.firstName} ${activeUser.lastName}
EMPLOYEE ID:   ${activeUser.employeeId}
PAY PERIOD:    ${slip.period}
ISSUE DATE:    ${slip.date}

--------------------------------------------------------
NET PAYABLE:   ${slip.net}
--------------------------------------------------------

STATUS: ${slip.status.toUpperCase()}

This document is encrypted and confidential.
Generated by SmartHRM PayPort Terminal.
--------------------------------------------------------`;

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Payslip_${slip.period.replace(/\s/g, '_')}_${activeUser.employeeId}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="flex flex-col h-full w-full bg-gray-50 font-sans p-4 sm:p-8 overflow-y-auto">
            {/* Header */}
            <div className="flex flex-col gap-2 mb-8">
                <div className="flex items-center gap-3">
                    <FileText className="text-blue-600 size-6 sm:size-8" />
                    <h1 className="text-xl sm:text-3xl font-black text-gray-800 italic uppercase tracking-tighter">My Payslip History</h1>
                </div>
                <p className="text-[10px] sm:text-xs font-black text-gray-400 uppercase tracking-[0.3em] ml-1">Confidential Financial Records :: Station {activeUser.employeeId || 'USR'}</p>
            </div>

            {/* Security Notice */}
            <div className="bg-blue-900 text-white p-4 sm:p-6 rounded-xl shadow-2xl mb-8 flex items-center gap-6 border-l-8 border-blue-400 relative overflow-hidden group">
                <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:scale-125 transition-transform duration-700">
                    <Lock size={80} />
                </div>
                <div className="bg-blue-800 p-3 rounded-lg shadow-inner">
                    <Lock size={28} className="text-blue-200" />
                </div>
                <div className="relative z-10">
                    <h3 className="text-sm sm:text-base font-black uppercase italic tracking-widest">Secure Document Access Protocol</h3>
                    <p className="text-[10px] sm:text-xs text-blue-200 mt-1 font-bold">
                        Your electronic payslips are AES-256 encrypted. Use your TRN Number to decrypt downloaded files.
                    </p>
                </div>
            </div>

            {/* Payslip List */}
            <div className="grid gap-4 sm:gap-6">
                {loading ? (
                    <div className="p-20 text-center italic font-black text-gray-300 uppercase tracking-[0.5em] animate-pulse">Requesting Secure Feed...</div>
                ) : history.length === 0 ? (
                    <div className="p-20 text-center italic font-black text-gray-300 uppercase tracking-[0.5em]">Inventory cache is currently empty.</div>
                ) : history.map((slip) => (
                    <div key={slip.id} className="bg-white p-4 sm:p-8 rounded-xl border-2 border-white border-r-gray-200 border-b-gray-200 shadow-xl hover:shadow-2xl hover:-translate-y-1 transition-all flex flex-col sm:flex-row items-center justify-between group">
                        <div className="flex items-center gap-6 w-full sm:w-auto mb-4 sm:mb-0">
                            <div className="w-14 h-14 sm:w-16 sm:h-16 bg-blue-50 border-2 border-white rounded-2xl flex items-center justify-center text-blue-600 shadow-inner group-hover:bg-blue-600 group-hover:text-white transition-colors">
                                <Calendar size={28} className="sm:size-32" />
                            </div>
                            <div className="flex flex-col">
                                <span className="text-xl sm:text-2xl font-black text-gray-800 italic uppercase tracking-tighter group-hover:text-blue-900">{slip.period}</span>
                                <span className="text-[10px] sm:text-xs font-bold text-gray-400 uppercase tracking-widest">Disbursement: {slip.date}</span>
                            </div>
                        </div>

                        <div className="flex items-center gap-8 w-full sm:w-auto justify-between sm:justify-end border-t sm:border-t-0 border-gray-100 pt-4 sm:pt-0">
                            <div className="flex flex-col items-end">
                                <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest italic">Net Remittance</span>
                                <span className="text-xl sm:text-2xl font-black text-blue-800 italic tabular-nums tracking-tighter">{slip.net}</span>
                            </div>
                            <button
                                onClick={() => handleDownload(slip)}
                                className="flex items-center gap-2 px-8 py-3 bg-blue-700 hover:bg-blue-800 text-white rounded-lg text-xs font-black uppercase italic tracking-widest shadow-lg active:translate-y-1 active:shadow-none transition-all border-b-4 border-blue-900"
                            >
                                <Download size={16} /> Download
                            </button>
                        </div>
                    </div>
                ))}
            </div>

            {/* Footer */}
            <div className="mt-auto pt-10 flex justify-center border-t border-gray-100 mt-12 pb-6">
                <p className="text-[10px] sm:text-xs text-gray-400 font-black uppercase italic tracking-widest">
                    Manual Verification Terminal :: <span className="text-blue-600 cursor-help underline decoration-dotted">DOCKET_ID_404</span>
                </p>
            </div>
        </div>
    );
};

export default MyPayslips;
